Feature: LeadPage Scenarios
@Lead @test20
Scenario: clickonLeadTab
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user waits for element "username"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
@Lead @test21
Scenario: clickonLeadTabandView
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user waits for element "username"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
Then click on button "View"
@Lead @test22
Scenario: clickonLeadTabandView
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user waits for element "username"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
Then select dropdown "View" "My Unread Leads"
Given user is on "LoginPage"
Then mousehover into element  "usermenu"
Then click on button "Logout"
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
Then click on button "Go"
@Lead @test23
Scenario: clickonLeadTabandTodayslead
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user waits for element "username"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
Then select dropdown "View" "Today's Leads"
@Lead @test24
Scenario: checkNewbuttononLeadsPage
Given user launch the application in "chrome"
Given user is on "LoginPage"
Then user waits for element "username"
Then user enter into the text box "username" "ambika@com.sand"
Then user enter into the text box "password" "Anoopkp@15"
Then click on button "Login"
Given user is on "LeadPage"
Then user waits for element "LeadTab"
Then click on button "LeadTab"
Then click on button "Newbutton"
Then enterintotextbox "Lastname" "ABCD"
Then enterintotextbox "Companyname" "ABCD"
Then click on button "save3"